# Generated by Django 3.1.7 on 2021-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_ru',
            field=models.CharField(default='...', max_length=200, verbose_name='answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_ru',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_bn',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_es',
            field=models.CharField(default='...', max_length=200),
        ),
    ]
