# Generated by Django 3.1.7 on 2021-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20210308_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_bn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_es',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_ru',
            field=models.CharField(max_length=200),
        ),
    ]
